<?php
return [
    'values'=>[
        'reference'=>12,
        'token'=>16,
        'password'=>8,
        'pagination'=>7,
        'one'=>1,
        'zero'=>0,
        'default'=>[
            'boolean'=>0
        ]
    ],
    'db'=>array(
        'size'=>array(
            'string'=>191,
            'name'=>[
                'organisation'=>100,
                'form'=>100,
            ],
            'description'=>[
                'organisation'=>255,
                'form'=>255,
                'section'=>255,
            ],
            'reference'=>[
                'organisation'=>15,
                'form'=>15
            ],
            'title'=>[
                'form'=>100,
                'section'=>100,
                'option'=>100
            ],
            'input'=>[
                'label'=>100,
                'placeholder'=>100
            ],

        )
    ),
    'pagination'=>array(
        'default'=>20,
        'organisation'=>20,
        'organisationtype'=>20
    ),
    'size'=>[
        'alias'=>[
            'branch'=>150,
            'category'=>150,
            'consumer'=>150,
            'counter'=>150,
            'organisation'=>150,
            'organisationtype'=>150,
            'role'=>150,
            'roletype'=>150,
            'solution'=>150,
            'user'=>150,

        ],
        'code'=>[
            'ticket'=>7,
            'organisation'=>3,
        ],
        'description'=>[
            'organisation'=>255,
            'organisationtype'=>255,
            'role'=>255,
            'roletype'=>255,
            'solution'=>255,
        ],
        'email'=>[
            'consumer'=>100,
            'user'=>100,
            'organisation'=>100,
        ],
        'mobile'=>[
            'consumer'=>20
        ],
        'min'=>[
            'password'=>8,
        ],
        'max'=>[
            'address'=>150,
            'contact'=>15,
            'comment'=>255,
            'description'=>255,
            'email'=>100,
            'fax'=>15,
            'ip'=>50,
            'mobile'=>20,
            'name'=>150,
            'location'=>100,
            'password'=>100,
            'plot'=>50,
            'ref'=>32,
            'text'=>100,
            'unit'=>10,
            'uuid'=>50


        ],
        'name'=>[
            'branch'=>100,
            'category'=>100,
            'consumer'=>100,
            'counter'=>100,
            'organisation'=>100,
            'organisationtype'=>100,
            'role'=>100,
            'roletype'=>100,
            'solution'=>100,
            'user'=>100,

        ],
        'otp'=>6,
        'password'=>12,
        'pagination'=>20,

        'pin'=>8,
        'ref'=>[
            'branch'=>12,
            'category'=>12,
            'checkin'=>12,
            'consumer'=>12,
            'counter'=>12,
            'device'=>12,
            'entry'=>12,
            'organisation'=>12,
            'organisationtype'=>12,
            'role'=>12,
            'roletype'=>12,
            'solution'=>12,
            'ticket'=>16,
            'user'=>12,
            'privilege'=>12,
            'feature'=>12,
            'section'=>12,
            'form'=>12,
            'inputtype'=>12,
            'input'=>12,
            'answer'=>12,
            'option'=>12,
        ],

        'maxint'=>999999999,
        'minint'=>0,
        'boolean'=>[
            'default'=>0,
            'true'=>1,
        ],
'countries'                     =>[
            'capital'=>255,
            'citizenship'=>255,
            'country_code'=>3,
            'currency'=>255,
            'currency_code'=>255,
            'currency_sub_unit'=>255,
            'currency_symbol'=>3,
            'full_name'=>255,
            'iso_3166_2'=>2,
            'iso_3166_3'=>3,
            'name'=>255,
            'region_code'=>3,
            'sub_region_code'=>3,
            'eea'                   =>0,
            'calling_code'=>3,
            'flag'=>6,
        ],

    ],

];